<?xml version="1.0" encoding="utf-8"?><Database Name="DBEcommerce" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-HRMC28G;Initial Catalog=DBEcommerce;Persist Security Info=True;User ID=sa;Trust Server Certificate=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="DBEcommerceConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="pathImg" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Products" ThisKey="id" OtherKey="CategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.WarrantyPolicies" Member="WarrantyPolicies">
    <Type Name="WarrantyPolicy">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImgProfile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="WarrantyProvider" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="WarrantyConditions" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PolicyContent" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DeletedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="WarrantyPolicy_Product" Member="Products" ThisKey="id" OtherKey="WarrantyPolicyID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Colors" Member="Colors">
    <Type Name="Color">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ColorName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Product_Color" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CountryOfOrigins" Member="CountryOfOrigins">
    <Type Name="CountryOfOrigin">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="CountryOfOrigin_Product" Member="Products" ThisKey="id" OtherKey="CountryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Customers" Member="Customers">
    <Type Name="Customer">
      <Column Name="id" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="BirthDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Customer_Review" Member="Reviews" ThisKey="id" OtherKey="CustomerID" Type="Review" />
      <Association Name="Customer_ShippingAddress" Member="ShippingAddresses" ThisKey="id" OtherKey="CustomerID" Type="ShippingAddress" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryReceiptDetails" Member="DeliveryReceiptDetails">
    <Type Name="DeliveryReceiptDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TotalPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="DeliveryReceipt_DeliveryReceiptDetail" Member="DeliveryReceipt" ThisKey="ReceiptID" OtherKey="id" Type="DeliveryReceipt" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_DeliveryReceiptDetail" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DeliveryReceipts" Member="DeliveryReceipts">
    <Type Name="DeliveryReceipt">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DeliveryDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="DeliveryReceipt_DeliveryReceiptDetail" Member="DeliveryReceiptDetails" ThisKey="id" OtherKey="ReceiptID" Type="DeliveryReceiptDetail" />
      <Association Name="Employee_DeliveryReceipt" Member="Employee" ThisKey="EmployeeID" OtherKey="id" Type="Employee" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Supplier_DeliveryReceipt" Member="Supplier" ThisKey="SupplierID" OtherKey="id" Type="Supplier" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DM_Screen" Member="DM_Screens">
    <Type Name="DM_Screen">
      <Column Name="ScreenCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScreenName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="DM_Screen_QL_PhanQuyen" Member="QL_PhanQuyens" ThisKey="ScreenCode" OtherKey="ScreenCode" Type="QL_PhanQuyen" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PositionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="DeletedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Employee_DeliveryReceipt" Member="DeliveryReceipts" ThisKey="id" OtherKey="EmployeeID" Type="DeliveryReceipt" />
      <Association Name="Employee_OrderCustomer" Member="OrderCustomers" ThisKey="id" OtherKey="EmployeeID" Type="OrderCustomer" />
      <Association Name="Employee_QL_UserGroup" Member="QL_UserGroups" ThisKey="id" OtherKey="IDEmployees" Type="QL_UserGroup" />
      <Association Name="Position_Employee" Member="Position" ThisKey="PositionID" OtherKey="id" Type="Position" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThuTu" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Product_Image" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manufacturers" Member="Manufacturers">
    <Type Name="Manufacturer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ManufacturerName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PathLogo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Manufacturer_Product" Member="Products" ThisKey="id" OtherKey="ManufacturerID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.OrderCustomers" Member="OrderCustomers">
    <Type Name="OrderCustomer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="OrderStatus" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PromotionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentStatus" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PaymentDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="AddressID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="OrderCustomer_OrderProductDetail" Member="OrderProductDetails" ThisKey="id" OtherKey="OrderID" Type="OrderProductDetail" />
      <Association Name="Employee_OrderCustomer" Member="Employee" ThisKey="EmployeeID" OtherKey="id" Type="Employee" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="PaymentMethod_OrderCustomer" Member="PaymentMethod" ThisKey="PaymentMethodID" OtherKey="id" Type="PaymentMethod" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Promotion_OrderCustomer" Member="Promotion" ThisKey="PromotionID" OtherKey="id" Type="Promotion" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="ShippingAddress_OrderCustomer" Member="ShippingAddress" ThisKey="AddressID" OtherKey="id" Type="ShippingAddress" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.OrderProductDetails" Member="OrderProductDetails">
    <Type Name="OrderProductDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UnitPrice" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Notes" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="OrderCustomer_OrderProductDetail" Member="OrderCustomer" ThisKey="OrderID" OtherKey="id" Type="OrderCustomer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_OrderProductDetail" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PaymentMethods" Member="PaymentMethods">
    <Type Name="PaymentMethod">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PaymentMethodName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="ApplicableFee" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="PaymentMethod_OrderCustomer" Member="OrderCustomers" ThisKey="id" OtherKey="PaymentMethodID" Type="OrderCustomer" />
    </Type>
  </Table>
  <Table Name="dbo.Positions" Member="Positions">
    <Type Name="Position">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PositionName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Position_Employee" Member="Employees" ThisKey="id" OtherKey="PositionID" Type="Employee" />
      <Association Name="Position_QL_PhanQuyen" Member="QL_PhanQuyens" ThisKey="id" OtherKey="IDPositions" Type="QL_PhanQuyen" />
      <Association Name="Position_QL_UserGroup" Member="QL_UserGroups" ThisKey="id" OtherKey="IDPositions" Type="QL_UserGroup" />
    </Type>
  </Table>
  <Table Name="dbo.ProductAttributeDetails" Member="ProductAttributeDetails">
    <Type Name="ProductAttributeDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="AttributeValue" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="ProductAttribute_ProductAttributeDetail" Member="ProductAttribute" ThisKey="AttributeID" OtherKey="id" Type="ProductAttribute" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_ProductAttributeDetail" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductAttributes" Member="ProductAttributes">
    <Type Name="ProductAttribute">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="AttributeName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="ProductAttribute_ProductAttributeDetail" Member="ProductAttributeDetails" ThisKey="id" OtherKey="AttributeID" Type="ProductAttributeDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ListedPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="RepresentativeImage" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PromotionalPrice" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Sold" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CategoryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WarrantyPolicyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ManufacturerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CountryID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Product_Color" Member="Colors" ThisKey="id" OtherKey="ProductID" Type="Color" />
      <Association Name="Product_DeliveryReceiptDetail" Member="DeliveryReceiptDetails" ThisKey="id" OtherKey="ProductID" Type="DeliveryReceiptDetail" />
      <Association Name="Product_Image" Member="Images" ThisKey="id" OtherKey="ProductID" Type="Image" />
      <Association Name="Product_OrderProductDetail" Member="OrderProductDetails" ThisKey="id" OtherKey="ProductID" Type="OrderProductDetail" />
      <Association Name="Product_ProductAttributeDetail" Member="ProductAttributeDetails" ThisKey="id" OtherKey="ProductID" Type="ProductAttributeDetail" />
      <Association Name="Product_ProductSupplierDetail" Member="ProductSupplierDetails" ThisKey="id" OtherKey="ProductID" Type="ProductSupplierDetail" />
      <Association Name="Product_Review" Member="Reviews" ThisKey="id" OtherKey="ProductID" Type="Review" />
      <Association Name="Category_Product" Member="Category" ThisKey="CategoryID" OtherKey="id" Type="Category" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="CountryOfOrigin_Product" Member="CountryOfOrigin" ThisKey="CountryID" OtherKey="id" Type="CountryOfOrigin" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Manufacturer_Product" Member="Manufacturer" ThisKey="ManufacturerID" OtherKey="id" Type="Manufacturer" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="WarrantyPolicy_Product" Member="WarrantyPolicy" ThisKey="WarrantyPolicyID" OtherKey="id" Type="WarrantyPolicy" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.ProductSupplierDetails" Member="ProductSupplierDetails">
    <Type Name="ProductSupplierDetail">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupplierID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StartDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Product_ProductSupplierDetail" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Supplier_ProductSupplierDetail" Member="Supplier" ThisKey="SupplierID" OtherKey="id" Type="Supplier" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Promotions" Member="Promotions">
    <Type Name="Promotion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImgProfile" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PromotionName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DiscountValue" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MinValue" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MaxDiscount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="EndDate" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="DeletedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DeletedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="UpdatedBy" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Promotion_OrderCustomer" Member="OrderCustomers" ThisKey="id" OtherKey="PromotionID" Type="OrderCustomer" />
    </Type>
  </Table>
  <Table Name="dbo.QL_PhanQuyen" Member="QL_PhanQuyens">
    <Type Name="QL_PhanQuyen">
      <Column Name="IDPositions" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ScreenCode" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="HasPermission" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Position_QL_PhanQuyen" Member="Position" ThisKey="IDPositions" OtherKey="id" Type="Position" IsForeignKey="true" />
      <Association Name="DM_Screen_QL_PhanQuyen" Member="DM_Screen" ThisKey="ScreenCode" OtherKey="ScreenCode" Type="DM_Screen" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.QL_UserGroup" Member="QL_UserGroups">
    <Type Name="QL_UserGroup">
      <Column Name="IDEmployees" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IDPositions" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Employee_QL_UserGroup" Member="Employee" ThisKey="IDEmployees" OtherKey="id" Type="Employee" IsForeignKey="true" />
      <Association Name="Position_QL_UserGroup" Member="Position" ThisKey="IDPositions" OtherKey="id" Type="Position" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reviews" Member="Reviews">
    <Type Name="Review">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReviewContent" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="RatingLevel" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ReviewDate" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="Bought" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Customer_Review" Member="Customer" ThisKey="CustomerID" OtherKey="id" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Product_Review" Member="Product" ThisKey="ProductID" OtherKey="id" Type="Product" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SequelizeMeta" Member="SequelizeMetas">
    <Type Name="SequelizeMeta">
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ShippingAddresses" Member="ShippingAddresses">
    <Type Name="ShippingAddress">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RecipientName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="SpecificAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CustomerID" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="ShippingAddress_OrderCustomer" Member="OrderCustomers" ThisKey="id" OtherKey="AddressID" Type="OrderCustomer" />
      <Association Name="Customer_ShippingAddress" Member="Customer" ThisKey="CustomerID" OtherKey="id" Type="Customer" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Suppliers" Member="Suppliers">
    <Type Name="Supplier">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupplierName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="createdAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Column Name="updatedAt" Type="System.DateTimeOffset" DbType="DateTimeOffset NOT NULL" CanBeNull="false" />
      <Association Name="Supplier_DeliveryReceipt" Member="DeliveryReceipts" ThisKey="id" OtherKey="SupplierID" Type="DeliveryReceipt" />
      <Association Name="Supplier_ProductSupplierDetail" Member="ProductSupplierDetails" ThisKey="id" OtherKey="SupplierID" Type="ProductSupplierDetail" />
    </Type>
  </Table>
</Database>